import React from "react";
import "./styles/globals.css";
import "./styles/index.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
